name: Python-practice-Test-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v3

      - name: 安裝 Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: 安裝套件
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y unzip openjdk-11-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: 啟動 Flask 測試伺服器
        env:
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_DB: ${{ secrets.PG_DB }}
        run: |
          python ./web/app.py > flask.log 2>&1 &
          sleep 5

      - name: 顯示 Flask 啟動記錄（flask.log）
        run: |
          cat flask.log

      - name: 執行測試
        env:
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_DB: ${{ secrets.PG_DB }}
        run: |
          python run_tests.py

      - name: 上傳測試結果（可加 Allure HTML）
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: ./reports

      - name: Copy Chrome report
        run: |
          mkdir -p public/allure/chrome
          cp -r reports/*/allure-report_chrome/* public/allure/chrome/

      - name: Copy Firefox report
        run: |
          mkdir -p public/allure/firefox
          cp -r reports/*/allure-report_firefox/* public/allure/firefox/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
