name: Docker UI Tests with Allure

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      # ✅ 產生 .env 檔（給容器用）
      - name: Generate .env from GitHub Secrets
        run: |
          echo "PG_HOST=${{ secrets.PG_HOST }}" >> .env
          echo "PG_PORT=${{ secrets.PG_PORT }}" >> .env
          echo "PG_USER=${{ secrets.PG_USER }}" >> .env
          echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env
          echo "PG_DB=${{ secrets.PG_DB }}" >> .env
          echo "FLASK_ENV=production" >> .env
          echo "BASE_URL=http://web:5000" >> .env

      # ✅ 啟動 Flask Web（背景模式）
      - name: Start Web Container
        run: make up

      # ✅ 執行測試容器
      - name: Run Selenium Tests
        run: make test

      - name: 上傳測試結果（可加 Allure HTML）
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: ./reports

      - name: Copy Chrome report
        if: always()
        run: |
          mkdir -p public/allure/chrome
          cp -r reports/*/allure-report_chrome/* public/allure/chrome/

      - name: Copy Firefox report
        if: always()
        run: |
          mkdir -p public/allure/firefox
          cp -r reports/*/allure-report_firefox/* public/allure/firefox/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
